pipeline {
  agent any

  tools {
    maven 'Maven'
    jdk 'JDK17'
  }

  stages {
    stage('Build') {
      steps {
        dir('demo') {
          bat 'mvn -B clean package -DskipTests'
        }
      }
    }

    stage('Test') {
      steps {
        dir('demo') {
          bat 'mvn -B test'
        }
      }
    }

    stage('SonarQube') {
      steps {
        dir('demo') {
          withCredentials([string(credentialsId: 'sonar-token', variable: 'SONAR_TOKEN')]) {
            bat 'mvn -B sonar:sonar -Dsonar.projectKey=student-crud -Dsonar.host.url=http://localhost:9000 -Dsonar.login=%SONAR_TOKEN%'
          }
        }
      }
    }

    stage('Docker Build') {
      steps {
        dir('demo') {
          bat 'docker build -t student-app:latest .'
        }
      }
    }
  }
}